apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: default
spec:
  project: default
  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: aws-load-balancer-controller
      targetRevision: 1.13.2
      helm:
        values: |
          clusterName: opwat-trainee-project-cluster
          region: ap-southeast-1

          vpcId: vpc-0ee1db43c91eda7c8

          serviceAccount:
            create: true
            name: aws-load-balancer-controller
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::026090549419:role/AmazonEKSLoadBalancerControllerRole

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
