apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-secrets
  namespace: default
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: coffeeshop
  source:
    repoURL: git@bitbucket.org:trainee_devops_intern/trainee-project.git
    targetRevision: main
    path: secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
