apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffeeshop-kitchen
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: "kitchen=026090549419.dkr.ecr.ap-southeast-1.amazonaws.com/kitchen"
    argocd-image-updater.argoproj.io/kitchen.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/kitchen.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/kitchen.update-strategy: semver
    argocd-image-updater.argoproj.io/pull-policy: Always
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/kitchen.force-update: "true"

spec:
  project: coffeeshop
  source:
    repoURL: git@bitbucket.org:trainee_devops_intern/trainee-project.git
    targetRevision: HEAD
    path: coffeeshop
    helm:
      valueFiles:
        - values/kitchen/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
 
