apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: default
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: external-dns
      targetRevision: 8.8.2
      helm:
        values: |
          provider: aws

          aws:
            zoneType: public

          txtOwnerId: external-dns-dev

          serviceAccount:
            name: external-dns
            create: true 
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::026090549419:role/ExternalDNSRole

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
