apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater
  namespace: default
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-image-updater 
      targetRevision: 0.12.1
      helm:
        values: |
          config:
            registries:
              - name: ECR
                api_url: https://026090549419.dkr.ecr.ap-southeast-1.amazonaws.com
                prefix: 026090549419.dkr.ecr.ap-southeast-1.amazonaws.com
                ping: yes
                insecure: false
                credentials: ext:/scripts/login.sh
                credsexpire: 10h

          authScripts:
            enabled: true
            scripts:
              login.sh: |
                #!/bin/sh
                HOME=/tmp aws ecr --region ap-southeast-1 get-authorization-token --output text --query 'authorizationData[].authorizationToken' | base64 -d 
          
          serviceAccount:
            create: true
            annotations:
               eks.amazonaws.com/role-arn: arn:aws:iam::026090549419:role/argoCDImageUpdaterRole
            name: argocd-image-updater
          
          


  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
