image:
  tag: latest
  pullPolicy: IfNotPresent
  repository: nginx

project:
  name: "coffeeshop"
  description: "Coffee Shop Application"
  sourceRepos:
    - "git@bitbucket.org:trainee_devops_intern/trainee-project.git"
  destinations:
    namespace: "default"
    server: "https://kubernetes.default.svc"

namespace:
  name: "default"

services:
  name: postgres
  repoURL: git@bitbucket.org:trainee_devops_intern/trainee-project.git
  targetRevision: main
  prune: true
  selfHeal: true
  path: coffeeshop
  # secretName: app-connection-secret
  port: 5672
  targetPort: 5672
  ingress:
    enabled: false
  env:
    - name: RABBITMQ_DEFAULT_USER
      value: "guest"
    - name: RABBITMQ_DEFAULT_PASS
      value: "guest"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
