image:
  tag: 1.0.0
  pullPolicy: IfNotPresent
  repository: 026090549419.dkr.ecr.ap-southeast-1.amazonaws.com/product

project:
  name: "coffeeshop"
  description: "Coffee Shop Application"
  sourceRepos:
    - "git@bitbucket.org:trainee_devops_intern/trainee-project.git"
  destinations:
    namespace: "default"
    server: "https://kubernetes.default.svc"

namespace:
  name: "default"

services:
  name: product
  repoURL: git@bitbucket.org:trainee_devops_intern/trainee-project.git
  targetRevision: main
  prune: true
  selfHeal: true
  path: coffeeshop
  port: 5001
  targetPort: 5001
  ingress:
    enabled: false
  env:
    - name: APP_NAME
      value: "product-service in docker"
  retry:
    limit: "3"
    backoff:
      duration: 5s
      factor: "2"
      maxDuration: "1m"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
