image:
  tag: 1.0.0  
  pullPolicy: IfNotPresent
  repository: 026090549419.dkr.ecr.ap-southeast-1.amazonaws.com/barista

project:
  name: "coffeeshop"
  description: "Coffee Shop Application"
  sourceRepos: 
    - "git@bitbucket.org:trainee_devops_intern/trainee-project.git"
  destinations:
    namespace: "default"
    server: "https://kubernetes.default.svc"

namespace:
  name: "default"

services:
  name: barista
  secretName: app-connection-secret
  
  port: 80
  targetPort: 80

  env:
    - name: APP_NAME
      value: "barista-service in docker"
    - name: IN_DOCKER
      value: "true"

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
